### ISSUE TITLE
ESXi: automatic datasdtore creation fails with NVME

### ISSUE THREAD

**Issue by alanbach** [canonical/packer-maas#190]
We recently came across a new issue where ESXi images when deployed using Flat storage layout type fail to create the automatic datastore if the underlying machine is using NVME disks. 

This issue does not happen when SATA disks are being used. 

We tested deployment on several different machine types and NVME seems to be the breaking point.

The deployment does finish w/o any complaints on MAAS side and you are able to go to VMWAre WebUI and create the datastore manually, however this breaks automation since a successful deployment is expected to come with a datastore already created. 

SSH'ing into the deployed ESXi units and inspecting maas.log shows the following trace:

```
Wiping current network configuration...
Done wiping network configuration!
Applying network configuration...
Configuring physical(eth0)...
Configuring static IPv4 address(10.1.8.53/21)
Configuring nameservers...
Done applying network configuration!
WARNING: Disk WD_BLACK SN770 500GB 22271H801573 not found!
WARNING: No storage information given, extending datastore1.
Traceback (most recent call last):
  File "/altbootbank/maas/storage-esxi", line 468, in <module>
    main()
  File "/altbootbank/maas/storage-esxi", line 458, in main
    extend_default(disks)
  File "/altbootbank/maas/storage-esxi", line 385, in extend_default
    p = Popen(["partedUtil", "fixGpt", dev_path], stdin=PIPE)
  File "/lib64/python3.8/subprocess.py", line 858, in __init__
  File "/lib64/python3.8/subprocess.py", line 1639, in _execute_child
TypeError: expected str, bytes or os.PathLike object, not NoneType
/var/lib/vmware/firstboot/001.firstboot_001: line 48: /altbootbank/maas/user-data: Operation not permitted
usage: vcenter [-h] [-c CONFIG] [-s SERVER] [-u USERNAME] [-p PASSWORD]
               [-D DATACENTER] [-H HOST] [-U ESXI_USERNAME] [-P ESXI_PASSWORD]
vcenter: error: the following fields are missing: vc_server, vc_username, vc_password

```

It would be great to find the source of the issue and get this resolved.

Thank you,
Alan

**Comment by alanbach** [comment]
I spent some time troubleshooting this issue, and seems like we are dealing with two separate problems.

1. The regex in get_disks() from storage-esxi fails to detect the serial numbers on NVME disks. Updating the regex as follows resolves this issue:

```diff
diff --git a/vmware-esxi/maas/storage-esxi b/vmware-esxi/maas/storage-esxi
index 1d9712c..75849d6 100755
--- a/vmware-esxi/maas/storage-esxi
+++ b/vmware-esxi/maas/storage-esxi
@@ -94,7 +94,7 @@ def get_disks():
     )
 
     serial_regex = re.compile(
-        r"^(?P<name>\S+?)__+(?P<model>\S+?)__+(?P<serial>\S+?)__+$"
+        r"^(?P<name>\S+?)__+(?P<model>\S+?)__+(?P<serial>\w+?)_*$"
     )
 
     for line in output.splitlines():
```

Testing with the original regex:
```
[{'name': 't10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00', 'other_names': ['vml.05b895f329562d0db2372fb123680911692fa791816c651592a7af720810d7dbbb', 'vml.0100000000374233385f374434425f384234345f314230300057445f424c41'], 'blocksize': 4096, 'serial': '', 'size': '476940 MB', 'path': '/vmfs/devices/disks/t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00', 'model': 'WD_BLACK SN770 500GB'}]
```

Testing with the new regex:
```
[{'name': 't10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00', 'other_names': ['vml.05b895f329562d0db2372fb123680911692fa791816c651592a7af720810d7dbbb', 'vml.0100000000374233385f374434425f384234345f314230300057445f424c41'], 'blocksize': 4096, 'serial': '7B387D4B8B441B00', 'size': '476940 MB', 'path': '/vmfs/devices/disks/t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00', 'model': 'WD_BLACK SN770 500GB'}]
```

I tested the regex with a previously tested non-NVME machine and it is also working fine:

```
[{'name': 't10.ATA_____QEMU_HARDDISK___________________________QM00001_____________', 'other_names': ['vml.0100000000514d30303030312020202020202020202020202051454d552048'], 'blocksize': 512, 'serial': 'QM00001', 'size': '35840 MB', 'path': '/vmfs/devices/disks/t10.ATA_____QEMU_HARDDISK___________________________QM00001_____________', 'model': 'QEMU HARDDISK'}, {'name': 't10.ATA_____QEMU_HARDDISK___________________________QM00003_____________', 'other_names': ['vml.0100000000514d30303030332020202020202020202020202051454d552048'], 'blocksize': 512, 'serial': 'QM00003', 'size': '51200 MB', 'path': '/vmfs/devices/disks/t10.ATA_____QEMU_HARDDISK___________________________QM00003_____________', 'model': 'QEMU HARDDISK'}]
```

This fixes the packer-maas side of the issue.

2. Now the second part of the issue: MAAS (3.3.5 Snap in my lab) is passing down a different serial number for the NVME disk. MAAS sees the serial number as 22271H801573 as seen below:

```
start: cmd-install/stage-partitioning/builtin/cmd-block-meta: curtin command block-meta
get_path_to_storage_volume for volume nvme0n1({'grub_device': True, 'id': 'nvme0n1', 'model': 'WD_BLACK SN770 500GB', 'name': 'nvme0n1', 'ptable': 'gpt', 'serial': '22271H801573', 'type': 'disk', 'wipe': 'superblock'})
Processing serial 22271H801573 via udev to 22271H801573
lookup_disks found: ['nvme-WD_BLACK_SN770_500GB_22271H801573', 'nvme-WD_BLACK_SN770_500GB_22271H801573_1', 'nvme-WD_BLACK_SN770_500GB_22271H801573-part1', 'nvme-WD_BLACK_SN770_500GB_22271H801573-part6', 'nvme-WD_BLACK_SN770_500GB_22271H801573-part5', 'nvme-WD_BLACK_SN770_500GB_22271H801573-part7', 'nvme-WD_BLACK_SN770_500GB_22271H801573_1-part1', 'nvme-WD_BLACK_SN770_500GB_22271H801573_1-part6', 'nvme-WD_BLACK_SN770_500GB_22271H801573_1-part5', 'nvme-WD_BLACK_SN770_500GB_22271H801573_1-part7']
Running command ['udevadm', 'info', '--query=property', '--export', '/dev/nvme0n1'] with allowed return codes [0] (capture=True)
````

Full output from machine read:

```json
"physicalblockdevice_set": [
        {
            "firmware_version": "731030WD",
            "used_for": "GPT partitioned with 2 partitions",
            "model": "WD_BLACK SN770 500GB",
            "type": "physical",
            "name": "nvme0n1",
            "id": 478,
            "storage_pool": null,
            "serial": "22271H801573",
            "uuid": null,
            "size": 500107862016,
            "block_size": 512,
            "system_id": "pqat7s",
            "tags": [
                "ssd"
            ],
            "path": "/dev/disk/by-dname/nvme0n1",
            "id_path": "/dev/disk/by-id/nvme-eui.e8238fa6bf530001001b448b4b7d387b",
            "filesystem": null,
            "used_size": 500104691712,
            "partitions": [
                {
                    "uuid": "cb4545ae-9580-47e2-9803-99babfee2742",
                    "size": 536870912,
                    "bootable": true,
                    "tags": [],
                    "id": 1299,
                    "device_id": 478,
                    "used_for": "fat32 formatted filesystem mounted at /boot/efi",
                    "path": "/dev/disk/by-dname/nvme0n1-part1",
                    "type": "partition",
                    "filesystem": {
                        "fstype": "fat32",
                        "label": "efi",
                        "uuid": "55127927-ecff-4dec-994e-e478cc78ab42",
                        "mount_point": "/boot/efi",
                        "mount_options": null
                    },
                    "system_id": "pqat7s",
                    "resource_uri": "/MAAS/api/2.0/nodes/pqat7s/blockdevices/478/partition/1299"
                },
                {
                    "uuid": "d18ff3a9-04b0-469d-989c-d997d5e5b76c",
                    "size": 499562577920,
                    "bootable": false,
                    "tags": [],
                    "id": 1300,
                    "device_id": 478,
                    "used_for": "ext4 formatted filesystem mounted at /",
                    "path": "/dev/disk/by-dname/nvme0n1-part2",
                    "type": "partition",
                    "filesystem": {
                        "fstype": "ext4",
                        "label": "root",
                        "uuid": "381ab43b-8df9-4dbd-93b7-eefb39bb8720",
                        "mount_point": "/",
                        "mount_options": null
                    },
                    "system_id": "pqat7s",
                    "resource_uri": "/MAAS/api/2.0/nodes/pqat7s/blockdevices/478/partition/1300"
                }
            ],
            "partition_table_type": "GPT",
            "numa_node": 0,
            "available_size": 0,
            "resource_uri": "/MAAS/api/2.0/nodes/pqat7s/blockdevices/478/"
        }
    ],
```

Which seems to be correct, when deploying Ubuntu and checking with Smartctl:

```bash
ubuntu@FJKTXM2:~$ sudo smartctl -i /dev/nvme0n1
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.0-91-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       WD_BLACK SN770 500GB
Serial Number:                      22271H801573
Firmware Version:                   731030WD
PCI Vendor/Subsystem ID:            0x15b7
IEEE OUI Identifier:                0x001b44
Total NVM Capacity:                 500,107,862,016 [500 GB]
Unallocated NVM Capacity:           0
Controller ID:                      0
NVMe Version:                       1.4
Number of Namespaces:               1
Namespace 1 Size/Capacity:          500,107,862,016 [500 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            001b44 8b4b7d387b
Local Time is:                      Sun Jan 14 01:02:10 2024 UTC
```

Opening the case and looking at the NVME, this serial number is correct.

In the deployed ESXi, manually changing the MAAS NVME serial number to ESXI NVME serial number in /altbootbank/maas/curtin.cfg and executing the command, completes the partitioning:

```
[root@FJKTXM2:/vmfs/volumes/aded4671-4f466a00-6788-2ee6102fd2ca/maas] ./storage-esxi -c /altbootbank/maas/curtin.cfg 
WARNING: No storage information given, extending datastore1.

FixGpt tries to fix any problems detected in GPT table.
Please ensure that you don't run this on any RDM (Raw Device Mapping) disk.
Are you sure you want to continue (Y/N): Error: The backup GPT table is not at the end of the disk, as it should be.  This might mean that another operating system believes the disk is smaller.  Fix, by moving the backup to the end (and removing the old backup)?
Fix/Ignore/Cancel? gpt
60801 255 63 976773168
1 64 204863 C12A7328F81F11D2BA4B00A0C93EC93B systemPartition 128
5 208896 8595455 EBD0A0A2B9E5443387C068B6B72699C7 linuxNative 0
6 8597504 16984063 EBD0A0A2B9E5443387C068B6B72699C7 linuxNative 0
7 16986112 67108830 4EB2EA3978554790A79EFAE495E21F8D vmfsl 0
gpt
60801 255 63 976773168
1 64 204863 C12A7328F81F11D2BA4B00A0C93EC93B 128
5 208896 8595455 EBD0A0A2B9E5443387C068B6B72699C7 0
6 8597504 16984063 EBD0A0A2B9E5443387C068B6B72699C7 0
7 16986112 67108830 4EB2EA3978554790A79EFAE495E21F8D 0
8 67108831 976773134 AA31E02A400F11DB9590000C2911D1B8 0
create fs deviceName:'/vmfs/devices/disks/t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00:8', fsShortName:'vmfs6', fsName:'datastore1'
deviceFullPath:/dev/disks/t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00:8 deviceFile:t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00:8
ATS on device /dev/disks/t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00:8: not supported
.
Checking if remote hosts are using this device as a valid file system. This may take a few seconds...
Creating vmfs6 file system on "t10.NVMe____WD_BLACK_SN770_500GB____________________7B387D4B8B441B00:8" with blockSize 1048576, unmapGranularity 1048576, unmapPriority default and volume label "datastore1".
Successfully created new volume: 65a32bbf-40c73586-a906-d89ef372ff72
INFO: Done applying storage configuration!
```

Ran out of time for today, I'll pick this up later, but wanted to send over my findings so far.
